/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BasePropertyValueEditor: typeof import('./src/features/wikibase-schema/components/BasePropertyValueEditor.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    ClaimEditor: typeof import('./src/features/wikibase-schema/components/ClaimEditor.vue')['default']
    Column: typeof import('primevue/column')['default']
    ColumnHeaderMenu: typeof import('./src/features/data-processing/components/ColumnHeaderMenu.vue')['default']
    ColumnPalette: typeof import('./src/features/data-processing/components/ColumnPalette.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CreateProject: typeof import('./src/features/project-management/pages/CreateProject.vue')['default']
    CustomPaginator: typeof import('./src/features/data-processing/components/CustomPaginator.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataTabPanel: typeof import('./src/features/data-processing/components/DataTabPanel.vue')['default']
    DefaultLayout: typeof import('./src/core/layouts/DefaultLayout.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DropZone: typeof import('./src/features/wikibase-schema/components/DropZone.vue')['default']
    Header: typeof import('./src/shared/components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainContent: typeof import('./src/shared/components/MainContent.vue')['default']
    OpenProject: typeof import('./src/features/project-management/pages/OpenProject.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ProjectView: typeof import('./src/features/project-management/pages/ProjectView.vue')['default']
    PropertySelector: typeof import('./src/features/wikibase-schema/components/PropertySelector.vue')['default']
    PropertyValueItem: typeof import('./src/features/wikibase-schema/components/PropertyValueItem.vue')['default']
    PropertyValueList: typeof import('./src/features/wikibase-schema/components/PropertyValueList.vue')['default']
    PropertyValueMappingEditor: typeof import('./src/features/wikibase-schema/components/PropertyValueMappingEditor.vue')['default']
    QualifiersEditor: typeof import('./src/features/wikibase-schema/components/QualifiersEditor.vue')['default']
    ReferenceContainer: typeof import('./src/features/wikibase-schema/components/ReferenceContainer.vue')['default']
    ReferencesEditor: typeof import('./src/features/wikibase-schema/components/ReferencesEditor.vue')['default']
    ReplaceDialog: typeof import('./src/features/data-processing/components/ReplaceDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaSelector: typeof import('./src/features/wikibase-schema/components/SchemaSelector.vue')['default']
    SchemaTabPanel: typeof import('./src/features/wikibase-schema/components/SchemaTabPanel.vue')['default']
    Select: typeof import('primevue/select')['default']
    Sidebar: typeof import('./src/shared/components/Sidebar.vue')['default']
    StatementEditor: typeof import('./src/features/wikibase-schema/components/StatementEditor.vue')['default']
    StatementManager: typeof import('./src/features/wikibase-schema/components/StatementManager.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TermSection: typeof import('./src/features/wikibase-schema/components/TermSection.vue')['default']
    TermsEditor: typeof import('./src/features/wikibase-schema/components/TermsEditor.vue')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    ValidationDisplay: typeof import('./src/features/wikibase-schema/components/ValidationDisplay.vue')['default']
    ValueMappingEditor: typeof import('./src/features/wikibase-schema/components/ValueMappingEditor.vue')['default']
    WikibaseSchemaEditor: typeof import('./src/features/wikibase-schema/components/WikibaseSchemaEditor.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
